worldc:
	g++ -std=c++11 -c world.h world.cpp
konduktorc:
	g++ -std=c++11 -c konduktorMakhlukHidup.h konduktorMakhlukHidup.cpp
adminc:
	g++ -std=c++11 -c administratorMakhlukHidup.h administratorMakhlukHidup.cpp
gerak:
	g++ -std=c++11 -o Gerak Gerak.cpp Gerak.h driverGerak.cpp Point.h Point.cpp
	
world:
	g++ -std=c++11 -c BurungUnta.h BurungUnta.cpp
	g++ -std=c++11 -c Gajah.h Gajah.cpp
	g++ -std=c++11 -c Harimau.h Harimau.cpp
	g++ -std=c++11 -c Hyena.h Hyena.cpp
	g++ -std=c++11 -c Mandril.h Mandril.cpp
	g++ -std=c++11 -c Beruang.h Beruang.cpp
	g++ -std=c++11 -c Omnivora.h Omnivora.cpp
	g++ -std=c++11 -c Karnivora.h Karnivora.cpp
	g++ -std=c++11 -c Herbivora.h Herbivora.cpp
	g++ -std=c++11 -c Tumbuhan.h Tumbuhan.cpp
	g++ -std=c++11 -c Hewan.h Hewan.cpp
	g++ -std=c++11 -c Manusia.h Manusia.cpp
	g++ -std=c++11 -c administratorMakhlukHidup.h administratorMakhlukHidup.cpp
	g++ -std=c++11 -c konduktorMakhlukHidup.h konduktorMakhlukHidup.cpp
	g++ -std=c++11 -c world.h world.cpp
	g++ -std=c++11 -o world driverWorld.cpp world.h world.cpp Point.h Point.cpp moderatorMakhlukHidup.cpp administratorMakhlukHidup.cpp konduktorMakhlukHidup.cpp Manusia.cpp MakhlukHidup.cpp HuntingSkill.cpp Gerak.cpp Polisi.cpp Hewan.cpp Herbivora.cpp Gajah.cpp Karnivora.cpp Hyena.cpp Omnivora.cpp Beruang.cpp
	
konduktor:
	g++ -std=c++11 -o driverKon konduktorMakhlukHidup.h konduktorMakhlukHidup.cpp driverKonduktor.cpp Manusia.cpp Gerak.cpp MakhlukHidup.cpp Point.cpp HuntingSkill.cpp

admin:
	g++ -std=c++11 -o driverAdmin administratorMakhlukHidup.cpp administratorMakhlukHidup.h driverAdmin.cpp Herbivora.cpp Herbivora.h Hewan.cpp Gerak.cpp HuntingSkill.cpp MakhlukHidup.cpp Point.cpp

karnivora :
	g++ -std=c++11 -o driverKarnivora driverKarnivora.cpp Karnivora.cpp Hewan.cpp Gerak.cpp HuntingSkill.cpp MakhlukHidup.cpp Point.cpp
polisic:
	g++ -std=c++11 -c Polisi.h Polisi.cpp
herbivora:
	g++ -std=c++11 -o driveHer driverHerbivora.cpp Herbivora.cpp MakhlukHidup.cpp Hewan.cpp HuntingSkill.cpp Gerak.cpp Point.cpp
	
MakhlukKarnivora :
	g++ -std=c++11 -o MakhlukKarnivora driverMakhlukKarnivora.cpp Harimau.cpp Hyena.cpp Karnivora.cpp Hewan.cpp Gerak.cpp HuntingSkill.cpp MakhlukHidup.cpp Point.cpp
	
omnivora:
	g++ -std=c++11 -o driverOmnivora driverOmnivora.cpp Omnivora.cpp MakhlukHidup.cpp Hewan.cpp HuntingSkill.cpp Gerak.cpp Point.cpp	
omnivorac:
	g++ -std=c++11 -c Omnivora.h Omnivora.cpp
karnivorac:
	g++ -std=c++11 -c Karnivora.h Karnivora.cpp
herbivorac:
	g++ -std=c++11 -c Herbivora.h Herbivora.cpp
hyenac:
	g++ -std=c++11 -c Hyena.h Hyena.cpp
harimauc:
	g++ -std=c++11 -c Harimau.h Harimau.cpp
gajahc:
	g++ -std=c++11 -c Gajah.h Gajah.cpp
burungc:
	g++ -std=c++11 -c BurungUnta.h BurungUnta.cpp
mandrilc:
	g++ -std=c++11 -c Mandril.h Mandril.cpp
bearc:
	g++ -std=c++11 -c Beruang.h Beruang.cpp

gajah:
	g++ -std=c++11 -o driverGajah driverGajah.cpp Gajah.cpp Herbivora.cpp MakhlukHidup.cpp Hewan.cpp HuntingSkill.cpp Gerak.cpp Point.cpp
burung:
	g++ -std=c++11 -o driverBurung driverBurungUnta.cpp BurungUnta.cpp Herbivora.cpp MakhlukHidup.cpp Hewan.cpp HuntingSkill.cpp Gerak.cpp Point.cpp
tumbuhan:
	g++ -std=c++11 -o driverT driverTumbuhan.cpp Tumbuhan.cpp Point.cpp MakhlukHidup.cpp
rumput:
	g++ -std=c++11 -o driverr driverRumput.cpp Rumput.cpp Tumbuhan.cpp Point.cpp MakhlukHidup.cpp
pohon:
	g++ -std=c++11 -o driverp driverPohon.cpp Pohon.cpp Tumbuhan.cpp Point.cpp MakhlukHidup.cpp