.TH "AdministratorMakhlukHidup" 3 "Thu Mar 3 2016" "Version 0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdministratorMakhlukHidup \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBKonduktorMakhlukHidup\fP, and \fBModeratorMakhlukHidup\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBfill\fP (int)"
.br
.ti -1c
.RI "void \fBpluck\fP (int)"
.br
.ti -1c
.RI "void \fBcreation\fP ()"
.br
.ti -1c
.RI "int \fBget_size\fP ()"
.br
.ti -1c
.RI "int \fBget_count\fP ()"
.br
.ti -1c
.RI "int * \fBget_daftar\fP ()"
.br
.ti -1c
.RI "int \fBget_daftar\fP (int i)"
.br
.ti -1c
.RI "void \fBset_size\fP (int)"
.br
.ti -1c
.RI "void \fBset_count\fP (int)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
