.TH "Gajah" 3 "Thu Mar 3 2016" "Version 0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Gajah \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHerbivora\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGajah\fP (const \fBGajah\fP &)"
.br
.ti -1c
.RI "\fBGajah\fP & \fBoperator=\fP (const \fBGajah\fP &)"
.br
.ti -1c
.RI "ifstream \fBoperator>>\fP (istream &)"
.br
.ti -1c
.RI "ofstream \fBoperator<<\fP (ostream &)"
.br
.ti -1c
.RI "void \fBmenua\fP ()"
.br
.ti -1c
.RI "void \fBgerak\fP ()"
.br
.ti -1c
.RI "bool \fBmati\fP ()"
.br
.ti -1c
.RI "void \fBdisplay\fP ()"
.br
.ti -1c
.RI "bool \fBLapar\fP ()"
.br
.ti -1c
.RI "bool \fBmemburu\fP ()"
.br
.ti -1c
.RI "void \fBberlari\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
