.TH "Gerak" 3 "Thu Mar 3 2016" "Version 0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Gerak \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBHewan\fP, and \fBManusia\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGerak\fP (int k=0, int a=0)"
.br
.ti -1c
.RI "\fBGerak\fP & \fBoperator=\fP (const \fBGerak\fP &)"
.br
.ti -1c
.RI "\fBPoint\fP \fBgerak_bebas\fP (\fBPoint\fP Awal)"
.br
.ti -1c
.RI "\fBPoint\fP \fBgerak_memburu\fP (\fBPoint\fP Awal, \fBPoint\fP Target)"
.br
.ti -1c
.RI "\fBPoint\fP \fBgerak_menjauh\fP (\fBPoint\fP Awal, \fBPoint\fP Predator)"
.br
.ti -1c
.RI "\fBPoint\fP \fBgerak_berarah\fP (\fBPoint\fP Awal, int _arah)"
.br
.ti -1c
.RI "void \fBset_Kecepatan\fP (int _kecepatan)"
.br
.ti -1c
.RI "void \fBset_Arah\fP (int _arah)"
.br
.ti -1c
.RI "int \fBget_Kecepatan\fP ()"
.br
.ti -1c
.RI "int \fBget_Arah\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
