.TH "Harimau" 3 "Thu Mar 3 2016" "Version 0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Harimau \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBkarnivora\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHarimau\fP (int x=0, int y=0)"
.br
.ti -1c
.RI "\fBHarimau\fP (const \fBHarimau\fP &)"
.br
.ti -1c
.RI "bool \fBmelambat\fP ()"
.br
.ti -1c
.RI "void \fBmenua\fP ()"
.br
.ti -1c
.RI "bool \fBmati\fP ()"
.br
.ti -1c
.RI "void \fBdisplay\fP ()"
.br
.ti -1c
.RI "bool \fBLapar\fP ()"
.br
.ti -1c
.RI "void \fBset_tingkat_kekenyangan\fP ()"
.br
.ti -1c
.RI "void \fBset_maks_tingkat_kekenyangan\fP ()"
.br
.ti -1c
.RI "void \fBget_tingkat_kekenyangan\fP ()"
.br
.ti -1c
.RI "void \fBget_maks_tingkat_kekenyangan\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
