.TH "Herbivora" 3 "Thu Mar 3 2016" "Version 0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Herbivora \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHewan\fP\&.
.PP
Inherited by \fBBurung_Unta\fP, and \fBGajah\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHerbivora\fP (int kec=0)"
.br
.ti -1c
.RI "\fBHerbivora\fP (const \fBHerbivora\fP &)"
.br
.ti -1c
.RI "\fBHerbivora\fP & \fBoperator=\fP (const \fBHerbivora\fP &)"
.br
.ti -1c
.RI "virtual int \fBget_deltaKecepatan\fP ()"
.br
.ti -1c
.RI "virtual void \fBset_deltaKecepatan\fP (int _deltaKecepatan)"
.br
.ti -1c
.RI "void \fBbergerak\fP (\fBMakhlukHidup\fP M)"
.br
.ti -1c
.RI "bool \fBisTarget\fP (\fBMakhlukHidup\fP M)"
.br
.ti -1c
.RI "bool \fBisPredator\fP (\fBMakhlukHidup\fP M)"
.br
.ti -1c
.RI "bool \fBLapar\fP ()"
.br
.ti -1c
.RI "bool \fBberlari\fP (\fBMakhlukHidup\fP M)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
