.TH "Hewan" 3 "Thu Mar 3 2016" "Version 0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hewan \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMakhlukHidup\fP, \fBHuntingSkill\fP, and \fBGerak\fP\&.
.PP
Inherited by \fBHerbivora\fP, \fBkarnivora\fP, and \fBOmnivora\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHewan\fP (int _umur=0, char _DNA= '*', int _ulangtahun=0, \fBPoint\fP P=PAwal, int kenyang=0, int maks=0)"
.br
.ti -1c
.RI "\fBHewan\fP (const \fBHewan\fP &)"
.br
.ti -1c
.RI "\fBHewan\fP & \fBoperator=\fP (const \fBHewan\fP &)"
.br
.ti -1c
.RI "void \fBsetLapar\fP ()"
.br
.ti -1c
.RI "void \fBset_tingkat_kekenyangan\fP (int kenyang)"
.br
.ti -1c
.RI "void \fBset_maks_tingkat_kekenyangan\fP (int maks)"
.br
.ti -1c
.RI "int \fBget_tingkat_kekenyangan\fP ()"
.br
.ti -1c
.RI "int \fBget_maks_tingkat_kekenyangan\fP ()"
.br
.ti -1c
.RI "bool \fBget_lapar\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
