.TH "HuntingSkill" 3 "Thu Mar 3 2016" "Version 0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HuntingSkill \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBHewan\fP, and \fBManusia\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHuntingSkill\fP (char *Target=NULL)"
.br
.ti -1c
.RI "\fBHuntingSkill\fP (const \fBHuntingSkill\fP &)"
.br
.ti -1c
.RI "\fBHuntingSkill\fP & \fBoperator=\fP (const \fBHuntingSkill\fP &)"
.br
.ti -1c
.RI "void \fBsetMemburu\fP (bool M)"
.br
.ti -1c
.RI "char * \fBgetTarget\fP ()"
.br
.ti -1c
.RI "bool \fBgetMemburu\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
