.TH "MakhlukHidup" 3 "Thu Mar 3 2016" "Version 0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MakhlukHidup \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBHewan\fP, and \fBManusia\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMakhlukHidup\fP (int _umur=0, char _DNA= '*', int _ulangtahun=0, \fBPoint\fP P=PAwal)"
.br
.ti -1c
.RI "\fBMakhlukHidup\fP (const \fBMakhlukHidup\fP &)"
.br
.ti -1c
.RI "\fBMakhlukHidup\fP & \fBoperator=\fP (const \fBMakhlukHidup\fP &)"
.br
.ti -1c
.RI "void \fBmenua\fP ()"
.br
.ti -1c
.RI "bool \fBmati\fP ()"
.br
.ti -1c
.RI "void \fBdisplay\fP ()"
.br
.ti -1c
.RI "int \fBget_umur\fP ()"
.br
.ti -1c
.RI "int \fBget_ulang_tahun\fP ()"
.br
.ti -1c
.RI "char \fBget_DNA\fP ()"
.br
.ti -1c
.RI "int \fBget_batas_umur\fP ()"
.br
.ti -1c
.RI "\fBPoint\fP \fBgetPosisi\fP ()"
.br
.ti -1c
.RI "char \fBgetPredator\fP (int i)"
.br
.ti -1c
.RI "int \fBgetUkuranPredator\fP ()"
.br
.ti -1c
.RI "void \fBset_umur\fP (int)"
.br
.ti -1c
.RI "void \fBset_ulang_tahun\fP (int)"
.br
.ti -1c
.RI "void \fBset_DNA\fP (char)"
.br
.ti -1c
.RI "void \fBsetPosisi\fP (\fBPoint\fP)"
.br
.ti -1c
.RI "void \fBsetPredator\fP (int i, char _predator)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
