.TH "Manusia" 3 "Thu Mar 3 2016" "Version 0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Manusia \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMakhlukHidup\fP, \fBHuntingSkill\fP, and \fBGerak\fP\&.
.PP
Inherited by \fBPolisi\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBsetMenghindar\fP (bool m)=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
