.TH "ModeratorMakhlukHidup" 3 "Thu Mar 3 2016" "Version 0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModeratorMakhlukHidup \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAdministratorMakhlukHidup\fP\&.
.PP
Inherited by \fBWorld\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsignalPosition\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
