.TH "Point" 3 "Thu Mar 3 2016" "Version 0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Point \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPoint\fP (int _x=0, int _y=0)"
.br
.ti -1c
.RI "\fBPoint\fP & \fBoperator=\fP (const \fBPoint\fP &)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBPoint\fP &)"
.br
.ti -1c
.RI "void \fBgeser\fP (int dx, int dy)"
.br
.ti -1c
.RI "int \fBgetAbsis\fP ()"
.br
.ti -1c
.RI "int \fBgetOrdinat\fP ()"
.br
.ti -1c
.RI "void \fBsetAbsis\fP (int _x)"
.br
.ti -1c
.RI "void \fBsetOrdinat\fP (int _y)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
