.TH "World" 3 "Thu Mar 3 2016" "Version 0.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
World \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBModeratorMakhlukHidup\fP, and \fBKonduktorMakhlukHidup\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitDisplay\fP ()"
.br
.ti -1c
.RI "void \fBupdateDisplay\fP ()"
.br
.ti -1c
.RI "bool \fBgameOver\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
